version: '3'

services:
  web:
    build: .
    environment:
      - SECRET_KEY=django-insecure--d@zzw!^omk!notmixl&0sd3z1i=08ttu16r)lzch0lb1)*pfm
      - DEBUG=1
    volumes:
      - .:/code
      - db.sqlite3
    ports:
      - "8000:8000"