version: 2.1
jobs:
  build-backend:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - restore_cache:
          keys: [docker-build]
      - run:
          command: |
            docker-compose -f docker-compose-ci.yml up -d --build
            docker-compose exec web python manage.py makemigrations
            docker-compose exec web python manage.py migrate
      - save_cache:
          key: docker-build
          paths:
            - "/logs"
  test-backend:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - restore_cache:
          keys: [docker-build]
      - run:
          name: Running tests
          command: |
            docker-compose -f docker-compose-ci.yml up -d --build
            docker-compose exec web python manage.py test
      - store_artifacts:
          path: test-reports/
          destination: note_app
workflows:
  build_test:
    jobs:
      - build-backend
      - test-backend:
          requires:
            - build-backend