version: 2.1
jobs:
  build-backend:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - restore_cache:
          key: desp1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            python manage.py makemigrations
            python manage.py migrate
      - save_cache:
          key: desp1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
  test-backend:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - restore_cache:
          key: desp1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Running tests
          command: |
            pipenv shell
            python3 manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app
workflows:
  build_test:
    jobs:
      - build-backend
      - test-backend:
          requires:
            - build-backend