version: 2.1
jobs:
  build-backend:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - restore_cache:
          key: desp1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            pip install pipenv && pipenv install --system
            python manage.py makemigrations
            python manage.py migrate
      - save_cache:
          key: desp1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
  test-backend:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - restore_cache:
          key: desp1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app
workflows:
  build_test:
    jobs:
      - build-backend
      - test-backend:
          requires:
            - build-backend