version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - restore_cache:
          key: desp1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            pipenv install -r requirements.txt
            pipenv shell
      - save_cache:
          key: desp1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            pipenv shell
            python3 manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app