version: 2.1
jobs:
  build-backend:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - restore_cache:
          key: desp1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            pipenv install -r requirements.txt
            pipenv shell
            python manage.py makemigrations
            python manage.py migrate
      - save_cache:
          key: desp1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "/"
  test-backend:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - restore_cache:
        key: desp1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Running tests
          command: |
            pipenv shell
            python3 manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app
workflows:
  jobs:
    - build-backend
    - test-backend:
        requires:
          - build-backend